---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: metrics-and-logging-monitor
#  labels:
#    release: prometheus-operator
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: metrics-and-logging
  endpoints:
    - port: management
      path: /actuator/prometheus
